inherited fmSchedule: TfmSchedule
  Left = 183
  Top = 106
  Width = 1039
  Height = 661
  Caption = #49828#52992#51460#46321#47197
  Font.Charset = HANGEUL_CHARSET
  Font.Height = -12
  FormStyle = fsMDIChild
  OldCreateOrder = True
  Position = poDefault
  Visible = True
  WindowState = wsMaximized
  OnClose = FormClose
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 12
  object GroupBox1: TGroupBox [0]
    Left = 0
    Top = 0
    Width = 217
    Height = 627
    Align = alLeft
    Caption = #49828#52992#51460#49324#50857#52636#51077#47928
    TabOrder = 0
    object sg_Door: TAdvStringGrid
      Left = 2
      Top = 14
      Width = 213
      Height = 611
      Cursor = crDefault
      Align = alClient
      ColCount = 1
      DefaultColWidth = 95
      DefaultRowHeight = 21
      FixedCols = 0
      RowCount = 2
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = []
      Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRangeSelect, goDrawFocusSelected, goColSizing, goEditing, goRowSelect]
      ParentFont = False
      ScrollBars = ssBoth
      TabOrder = 0
      OnClick = sg_DoorClick
      OnCheckBoxClick = sg_DoorCheckBoxClick
      ActiveCellFont.Charset = DEFAULT_CHARSET
      ActiveCellFont.Color = clWindowText
      ActiveCellFont.Height = -11
      ActiveCellFont.Name = 'Tahoma'
      ActiveCellFont.Style = [fsBold]
      ColumnHeaders.Strings = (
        #52636#51077#47928)
      ControlLook.FixedGradientHoverFrom = clGray
      ControlLook.FixedGradientHoverTo = clWhite
      ControlLook.FixedGradientDownFrom = clGray
      ControlLook.FixedGradientDownTo = clSilver
      ControlLook.DropDownHeader.Font.Charset = DEFAULT_CHARSET
      ControlLook.DropDownHeader.Font.Color = clWindowText
      ControlLook.DropDownHeader.Font.Height = -11
      ControlLook.DropDownHeader.Font.Name = 'Tahoma'
      ControlLook.DropDownHeader.Font.Style = []
      ControlLook.DropDownHeader.Visible = True
      ControlLook.DropDownHeader.Buttons = <>
      ControlLook.DropDownFooter.Font.Charset = DEFAULT_CHARSET
      ControlLook.DropDownFooter.Font.Color = clWindowText
      ControlLook.DropDownFooter.Font.Height = -11
      ControlLook.DropDownFooter.Font.Name = 'MS Sans Serif'
      ControlLook.DropDownFooter.Font.Style = []
      ControlLook.DropDownFooter.Visible = True
      ControlLook.DropDownFooter.Buttons = <>
      Filter = <>
      FilterDropDown.Font.Charset = DEFAULT_CHARSET
      FilterDropDown.Font.Color = clWindowText
      FilterDropDown.Font.Height = -11
      FilterDropDown.Font.Name = 'MS Sans Serif'
      FilterDropDown.Font.Style = []
      FilterDropDownClear = '(All)'
      FixedColWidth = 181
      FixedFont.Charset = DEFAULT_CHARSET
      FixedFont.Color = clWindowText
      FixedFont.Height = -11
      FixedFont.Name = 'Tahoma'
      FixedFont.Style = [fsBold]
      FloatFormat = '%.2f'
      PrintSettings.DateFormat = 'dd/mm/yyyy'
      PrintSettings.Font.Charset = DEFAULT_CHARSET
      PrintSettings.Font.Color = clWindowText
      PrintSettings.Font.Height = -11
      PrintSettings.Font.Name = 'MS Sans Serif'
      PrintSettings.Font.Style = []
      PrintSettings.FixedFont.Charset = DEFAULT_CHARSET
      PrintSettings.FixedFont.Color = clWindowText
      PrintSettings.FixedFont.Height = -11
      PrintSettings.FixedFont.Name = 'MS Sans Serif'
      PrintSettings.FixedFont.Style = []
      PrintSettings.HeaderFont.Charset = DEFAULT_CHARSET
      PrintSettings.HeaderFont.Color = clWindowText
      PrintSettings.HeaderFont.Height = -11
      PrintSettings.HeaderFont.Name = 'MS Sans Serif'
      PrintSettings.HeaderFont.Style = []
      PrintSettings.FooterFont.Charset = DEFAULT_CHARSET
      PrintSettings.FooterFont.Color = clWindowText
      PrintSettings.FooterFont.Height = -11
      PrintSettings.FooterFont.Name = 'MS Sans Serif'
      PrintSettings.FooterFont.Style = []
      PrintSettings.PageNumSep = '/'
      ScrollSynch = True
      SearchFooter.FindNextCaption = 'Find next'
      SearchFooter.FindPrevCaption = 'Find previous'
      SearchFooter.Font.Charset = DEFAULT_CHARSET
      SearchFooter.Font.Color = clWindowText
      SearchFooter.Font.Height = -11
      SearchFooter.Font.Name = 'MS Sans Serif'
      SearchFooter.Font.Style = []
      SearchFooter.HighLightCaption = 'Highlight'
      SearchFooter.HintClose = 'Close'
      SearchFooter.HintFindNext = 'Find next occurence'
      SearchFooter.HintFindPrev = 'Find previous occurence'
      SearchFooter.HintHighlight = 'Highlight occurences'
      SearchFooter.MatchCaseCaption = 'Match case'
      Version = '6.0.4.4'
      ColWidths = (
        181)
    end
  end
  object Panel1: TPanel [1]
    Left = 217
    Top = 0
    Width = 814
    Height = 627
    Align = alClient
    TabOrder = 1
    object gb_Schedule: TGroupBox
      Left = 1
      Top = 1
      Width = 812
      Height = 625
      Align = alClient
      Caption = #49828#52992#51460
      TabOrder = 0
      object Panel2: TPanel
        Left = 2
        Top = 14
        Width = 808
        Height = 43
        Align = alTop
        TabOrder = 0
        object btn_scheduleSearch: TSpeedButton
          Left = 16
          Top = 5
          Width = 153
          Height = 33
          Caption = #49828#52992#51460#51312#54924
          OnClick = btn_scheduleSearchClick
        end
        object btn_ScheduleReg: TSpeedButton
          Left = 192
          Top = 5
          Width = 153
          Height = 33
          Caption = #49828#52992#51460#46321#47197
          OnClick = btn_ScheduleRegClick
        end
        object Label1: TLabel
          Left = 352
          Top = 15
          Width = 72
          Height = 12
          Caption = #49440#53469#46108#52636#51077#47928
        end
        object Panel31: TPanel
          Left = 540
          Top = 10
          Width = 50
          Height = 23
          Caption = #52488#44592#54868
          TabOrder = 0
          OnClick = Panel31Click
        end
        object Panel32: TPanel
          Tag = 1
          Left = 589
          Top = 10
          Width = 50
          Height = 23
          Caption = #44060#48169
          Color = clGreen
          DragMode = dmAutomatic
          TabOrder = 1
        end
        object Panel33: TPanel
          Tag = 1
          Left = 639
          Top = 10
          Width = 50
          Height = 23
          Caption = #50868#50689
          Color = clAqua
          DragMode = dmAutomatic
          TabOrder = 2
        end
        object Panel34: TPanel
          Tag = 1
          Left = 689
          Top = 10
          Width = 50
          Height = 23
          Caption = #54224#49604
          Color = clRed
          DragMode = dmAutomatic
          TabOrder = 3
        end
        object stDoor: TStaticText
          Left = 432
          Top = 15
          Width = 97
          Height = 12
          Alignment = taCenter
          AutoSize = False
          BorderStyle = sbsSunken
          Font.Charset = HANGEUL_CHARSET
          Font.Color = clWindowText
          Font.Height = -12
          Font.Name = #44404#47548#52404
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 4
        end
        object Panel3: TPanel
          Tag = 1
          Left = 739
          Top = 10
          Width = 50
          Height = 23
          Caption = #47560#49828#53552
          Color = clPurple
          DragMode = dmAutomatic
          TabOrder = 5
        end
      end
      object gb1: TGroupBox
        Left = 2
        Top = 57
        Width = 808
        Height = 88
        Align = alTop
        Caption = #54217#51068
        TabOrder = 1
        object pb_graph1: TPaintBox
          Left = 9
          Top = 16
          Width = 768
          Height = 17
          Hint = '1'
          Color = 15198183
          ParentColor = False
          OnPaint = pb_graph1Paint
        end
        object lb_time11: TLabel
          Left = 78
          Top = 16
          Width = 51
          Height = 16
          Caption = 'Label1'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time12: TLabel
          Left = 136
          Top = 65
          Width = 51
          Height = 16
          Caption = 'Label2'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time14: TLabel
          Left = 258
          Top = 65
          Width = 51
          Height = 16
          Caption = 'Label4'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time13: TLabel
          Left = 197
          Top = 16
          Width = 42
          Height = 16
          Caption = '12:23'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object pan_Day1: TPanel
          Left = 8
          Top = 34
          Width = 769
          Height = 33
          TabOrder = 0
          object panTime11: TPanel
            Tag = 1
            Left = 1
            Top = 1
            Width = 89
            Height = 31
            Hint = '1'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 0
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object pan_tab: TPanel
              Tag = 2
              Left = 84
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '1'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime14: TPanel
            Tag = 1
            Left = 210
            Top = 1
            Width = 60
            Height = 31
            Hint = '1'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 1
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel17: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '1'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime15: TPanel
            Tag = 1
            Left = 270
            Top = 1
            Width = 497
            Height = 31
            Hint = '1'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 2
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
          end
          object panTime13: TPanel
            Tag = 1
            Left = 150
            Top = 1
            Width = 60
            Height = 31
            Hint = '1'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 3
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel20: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '1'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime12: TPanel
            Tag = 1
            Left = 90
            Top = 1
            Width = 60
            Height = 31
            Hint = '1'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 4
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel22: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '1'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
        end
      end
      object gb2: TGroupBox
        Left = 2
        Top = 145
        Width = 808
        Height = 88
        Align = alTop
        Caption = #53664#50836#51068
        TabOrder = 2
        object pb_graph2: TPaintBox
          Left = 9
          Top = 16
          Width = 768
          Height = 17
          Hint = '2'
          Color = 15198183
          ParentColor = False
          OnPaint = pb_graph1Paint
        end
        object lb_time21: TLabel
          Left = 78
          Top = 16
          Width = 51
          Height = 16
          Caption = 'Label1'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time22: TLabel
          Left = 136
          Top = 65
          Width = 51
          Height = 16
          Caption = 'Label2'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time24: TLabel
          Left = 258
          Top = 65
          Width = 51
          Height = 16
          Caption = 'Label4'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time23: TLabel
          Left = 197
          Top = 16
          Width = 42
          Height = 16
          Caption = '12:23'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object pan_Day2: TPanel
          Left = 8
          Top = 34
          Width = 769
          Height = 33
          TabOrder = 0
          object panTime21: TPanel
            Tag = 1
            Left = 1
            Top = 1
            Width = 89
            Height = 31
            Hint = '2'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 0
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel25: TPanel
              Tag = 2
              Left = 84
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '2'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime24: TPanel
            Tag = 1
            Left = 210
            Top = 1
            Width = 60
            Height = 31
            Hint = '2'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 1
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel27: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '2'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime25: TPanel
            Tag = 1
            Left = 270
            Top = 1
            Width = 497
            Height = 31
            Hint = '2'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 2
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
          end
          object panTime23: TPanel
            Tag = 1
            Left = 150
            Top = 1
            Width = 60
            Height = 31
            Hint = '2'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 3
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel30: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '2'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime22: TPanel
            Tag = 1
            Left = 90
            Top = 1
            Width = 60
            Height = 31
            Hint = '2'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 4
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel36: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '2'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
        end
      end
      object gb3: TGroupBox
        Left = 2
        Top = 233
        Width = 808
        Height = 88
        Align = alTop
        Caption = #51068#50836#51068
        TabOrder = 3
        object pb_graph3: TPaintBox
          Left = 9
          Top = 16
          Width = 768
          Height = 17
          Hint = '3'
          Color = 15198183
          ParentColor = False
          OnPaint = pb_graph1Paint
        end
        object lb_time31: TLabel
          Left = 78
          Top = 16
          Width = 51
          Height = 16
          Caption = 'Label1'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time32: TLabel
          Left = 136
          Top = 65
          Width = 51
          Height = 16
          Caption = 'Label2'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time34: TLabel
          Left = 258
          Top = 65
          Width = 51
          Height = 16
          Caption = 'Label4'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time33: TLabel
          Left = 197
          Top = 16
          Width = 42
          Height = 16
          Caption = '12:23'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object pan_Day3: TPanel
          Left = 8
          Top = 34
          Width = 769
          Height = 33
          TabOrder = 0
          object panTime31: TPanel
            Tag = 1
            Left = 1
            Top = 1
            Width = 89
            Height = 31
            Hint = '3'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 0
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel39: TPanel
              Tag = 2
              Left = 84
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '3'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime34: TPanel
            Tag = 1
            Left = 210
            Top = 1
            Width = 60
            Height = 31
            Hint = '3'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 1
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel41: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '3'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime35: TPanel
            Tag = 1
            Left = 270
            Top = 1
            Width = 497
            Height = 31
            Hint = '3'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 2
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
          end
          object panTime33: TPanel
            Tag = 1
            Left = 150
            Top = 1
            Width = 60
            Height = 31
            Hint = '3'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 3
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel44: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '3'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime32: TPanel
            Tag = 1
            Left = 90
            Top = 1
            Width = 60
            Height = 31
            Hint = '3'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 4
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel46: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '3'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
        end
      end
      object gb4: TGroupBox
        Left = 2
        Top = 321
        Width = 808
        Height = 88
        Align = alTop
        Caption = #53945#51221#51068'1'
        TabOrder = 4
        object pb_graph4: TPaintBox
          Left = 9
          Top = 16
          Width = 768
          Height = 17
          Hint = '4'
          Color = 15198183
          ParentColor = False
          OnPaint = pb_graph1Paint
        end
        object lb_time41: TLabel
          Left = 78
          Top = 16
          Width = 51
          Height = 16
          Caption = 'Label1'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time42: TLabel
          Left = 136
          Top = 65
          Width = 51
          Height = 16
          Caption = 'Label2'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time44: TLabel
          Left = 258
          Top = 65
          Width = 51
          Height = 16
          Caption = 'Label4'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time43: TLabel
          Left = 197
          Top = 16
          Width = 42
          Height = 16
          Caption = '12:23'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object pan_Day4: TPanel
          Left = 8
          Top = 34
          Width = 769
          Height = 33
          TabOrder = 0
          object panTime41: TPanel
            Tag = 1
            Left = 1
            Top = 1
            Width = 89
            Height = 31
            Hint = '4'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 0
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel49: TPanel
              Tag = 2
              Left = 84
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '4'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime44: TPanel
            Tag = 1
            Left = 210
            Top = 1
            Width = 60
            Height = 31
            Hint = '4'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 1
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel51: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '4'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime45: TPanel
            Tag = 1
            Left = 270
            Top = 1
            Width = 497
            Height = 31
            Hint = '4'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 2
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
          end
          object panTime43: TPanel
            Tag = 1
            Left = 150
            Top = 1
            Width = 60
            Height = 31
            Hint = '4'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 3
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel54: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '4'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime42: TPanel
            Tag = 1
            Left = 90
            Top = 1
            Width = 60
            Height = 31
            Hint = '4'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 4
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel56: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '4'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
        end
      end
      object pan_Msg: TPanel
        Left = 2
        Top = 585
        Width = 808
        Height = 38
        Align = alClient
        Font.Charset = HANGEUL_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #44404#47548#52404
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 5
        object Label2: TLabel
          Left = 16
          Top = 8
          Width = 753
          Height = 25
          Alignment = taCenter
          AutoSize = False
          Caption = #49324#50857#48277' : '#54644#45817' '#49828#52992#51460#48148#47484' '#45908#48660' '#53364#47533' '#54616#49884#47732' '#45796#51020' '#47784#46300#47196' '#48320#44221' '#46121#45768#45796'.'
          Font.Charset = HANGEUL_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = #44404#47548#52404
          Font.Style = [fsBold]
          ParentFont = False
        end
      end
      object gb6: TGroupBox
        Left = 2
        Top = 497
        Width = 808
        Height = 88
        Align = alTop
        Caption = #53945#51221#51068'3'
        TabOrder = 6
        object pb_graph6: TPaintBox
          Left = 9
          Top = 16
          Width = 768
          Height = 17
          Hint = '6'
          Color = 15198183
          ParentColor = False
          OnPaint = pb_graph1Paint
        end
        object lb_time61: TLabel
          Left = 78
          Top = 16
          Width = 74
          Height = 16
          Caption = 'lb_time61'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time62: TLabel
          Left = 136
          Top = 65
          Width = 74
          Height = 16
          Caption = 'lb_time62'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time64: TLabel
          Left = 258
          Top = 65
          Width = 74
          Height = 16
          Caption = 'lb_time64'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time63: TLabel
          Left = 197
          Top = 16
          Width = 42
          Height = 16
          Caption = '12:23'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object pan_Day6: TPanel
          Left = 8
          Top = 34
          Width = 769
          Height = 33
          TabOrder = 0
          object panTime61: TPanel
            Tag = 1
            Left = 1
            Top = 1
            Width = 89
            Height = 31
            Hint = '6'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 0
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel5: TPanel
              Tag = 2
              Left = 84
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '6'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime64: TPanel
            Tag = 1
            Left = 210
            Top = 1
            Width = 60
            Height = 31
            Hint = '6'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 1
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel7: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '6'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime65: TPanel
            Tag = 1
            Left = 270
            Top = 1
            Width = 497
            Height = 31
            Hint = '6'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 2
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
          end
          object panTime63: TPanel
            Tag = 1
            Left = 150
            Top = 1
            Width = 60
            Height = 31
            Hint = '6'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 3
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel13: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '6'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime62: TPanel
            Tag = 1
            Left = 90
            Top = 1
            Width = 60
            Height = 31
            Hint = '6'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 4
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel15: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '6'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
        end
      end
      object gb5: TGroupBox
        Left = 2
        Top = 409
        Width = 808
        Height = 88
        Align = alTop
        Caption = #53945#51221#51068'2'
        TabOrder = 7
        object pb_graph5: TPaintBox
          Left = 9
          Top = 16
          Width = 768
          Height = 17
          Hint = '5'
          Color = 15198183
          ParentColor = False
          OnPaint = pb_graph1Paint
        end
        object lb_time51: TLabel
          Left = 78
          Top = 16
          Width = 51
          Height = 16
          Caption = 'Label1'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time52: TLabel
          Left = 136
          Top = 65
          Width = 51
          Height = 16
          Caption = 'Label2'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time54: TLabel
          Left = 258
          Top = 65
          Width = 51
          Height = 16
          Caption = 'Label4'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lb_time53: TLabel
          Left = 197
          Top = 16
          Width = 42
          Height = 16
          Caption = '12:23'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = 'System'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object pan_Day5: TPanel
          Left = 8
          Top = 34
          Width = 769
          Height = 33
          TabOrder = 0
          object panTime51: TPanel
            Tag = 1
            Left = 1
            Top = 1
            Width = 89
            Height = 31
            Hint = '5'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 0
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel59: TPanel
              Tag = 2
              Left = 84
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '5'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime54: TPanel
            Tag = 1
            Left = 210
            Top = 1
            Width = 60
            Height = 31
            Hint = '5'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 1
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel61: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '5'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime55: TPanel
            Tag = 1
            Left = 270
            Top = 1
            Width = 497
            Height = 31
            Hint = '5'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 2
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
          end
          object panTime53: TPanel
            Tag = 1
            Left = 150
            Top = 1
            Width = 60
            Height = 31
            Hint = '5'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 3
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel64: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '5'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
          object panTime52: TPanel
            Tag = 1
            Left = 90
            Top = 1
            Width = 60
            Height = 31
            Hint = '5'
            Align = alLeft
            BevelOuter = bvLowered
            Color = clAqua
            ParentShowHint = False
            ShowHint = True
            TabOrder = 4
            OnDblClick = panTime11DblClick
            OnDragDrop = panTime11DragDrop
            OnDragOver = panTime11DragOver
            OnResize = panTime11Resize
            object Panel66: TPanel
              Tag = 2
              Left = 55
              Top = 1
              Width = 4
              Height = 29
              Cursor = crSizeWE
              Hint = '5'
              Align = alRight
              BevelOuter = bvNone
              TabOrder = 0
              OnMouseMove = pan_tabMouseMove
            end
          end
        end
      end
    end
  end
  object pan_Gauge: TPanel [2]
    Left = 232
    Top = 296
    Width = 681
    Height = 57
    TabOrder = 2
    Visible = False
    object Gauge_schedule: TGauge
      Left = 16
      Top = 32
      Width = 649
      Height = 17
      ForeColor = clBlue
      Progress = 0
    end
    object lb_msg: TLabel
      Left = 16
      Top = 8
      Width = 36
      Height = 12
      Caption = 'lb_msg'
    end
  end
end
